import streamlit as st
import requests
from dotenv import load_dotenv
import openai
import json

load_dotenv()

st.title('MelodicMind - Add Memory')

st.write('Think of a memory you want to remember and fill in the details below.')

# Ask the user for memory details
memory_description = st.text_area("Memory Description", "Enter your memory description here...")
memory_image = st.file_uploader("Upload an image for the memory (optional)", type=["jpg", "jpeg", "png"])

# Function to make a stable diffusion request and display the result
def make_stable_diffusion_request(description):
    url = f"https://516d-34-125-105-189.ngrok-free.app/predict?prompt={description}"
    response = requests.get(url)
    print(json.loads(response.text)['url'])
    return json.loads(response.text)['url']

# Handle the user's input and make the Stable Diffusion request if needed
if st.button("Add Memory"):
    if not memory_description.strip():
        st.warning("Please enter a memory description.")
    else:
        st.info("Adding memory...")

        if not memory_image:
            # Make a Stable Diffusion request based on the memory description
            stable_diffusion_image_url = make_stable_diffusion_request(memory_description)
            st.success("Memory added successfully!")

            # Display the image generated by Stable Diffusion (if available)
            if stable_diffusion_image_url:
                st.image(stable_diffusion_image_url, caption='Stable Diffusion Result', use_column_width=True)
            else:
                st.warning("No image generated by Stable Diffusion.")
        
        if memory_image: 
            pass
        else:
            pass
